[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
version = "0.23.3"
name = "absbox"
description = "an analytical library for cashflow modeling on ABS/MBS products"
readme = "README.md"

authors = [
  {email = "always.zhang@gmail.com"},
  {name = "xiaoyu, zhang"}
]

dependencies = [
    "pandas ==1.4.3",
    "numpy ==1.23.1",
    "matplotlib",
    "requests",
    "rich",
    "pyxirr",
    "pyspecter",
    "graphviz"
]

[project.urls]
homepage = "https://absbox.org"
documentation = "https://absbox-doc.readthedocs.io/en/latest/"
repository = "https://github.com/yellowbean/AbsBox/"




[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "absbox/tests",
]

[project.optional-dependencies]
test = [
    "pytest",
    "jsondiff",
    "deepdiff",
]
